// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
// import { CartContext } from "./context/CartContext";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [cart, setCart] = useState([]);
  return (
    <ClerkProvider>
      {/* <CartContext.Provider value={{cart,setCart}}> */}
      <html lang="en" className="h-full ">
        <body
          className={cn(
            "elative h-full font-sans antialiased",
            inter.className
          )}
        >
          <main className="relative flex flex-col min-h-screen">
            <Navbar />
            <div className="flex-grow flex-1">{children}</div>
          </main>
        </body>
      </html>
      {/* </CartContext> */}
    </ClerkProvider>
  );
}
